dist: focal
language: ruby
rvm:
 - 2.6.3
services:
  - postgresql
addons:
  postgresql: "13"
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13
env:
  matrix:
    - TEST_SUITE=rspec
  global:
  - PGPORT=5433
  - PGUSER=travis
before_script:
  - cp -f config/database.yml.travis config/database.yml
  - export TZ=America/New_York
script:
  - bundle exec rake db:test:prepare
  - bundle exec $TEST_SUITE
